# Generated by Django 4.2.1 on 2023-05-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_folder_name_en_folder_name_ru_folder_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='image',
            field=models.ImageField(null=True, upload_to='folder/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Image'),
        ),
    ]
