# Generated by Django 4.2.1 on 2023-05-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_folder_image_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.CharField(max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.CharField(max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=models.CharField(max_length=256, null=True, verbose_name='Description'),
        ),
    ]
