# Generated by Django 4.2.1 on 2023-05-24 13:00

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_description_news_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='folder/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='gallery/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='banner',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='banner/', verbose_name='Banner'),
        ),
    ]
