# Generated by Django 4.2.1 on 2023-05-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_country_name_en_country_name_ru_country_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='icon',
        ),
    ]
