# Generated by Django 4.2.1 on 2023-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityofyourcompany',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='activityofyourcompany',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='activityofyourcompany',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='choiceofservice',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='choiceofservice',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='choiceofservice',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='hearingus',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='hearingus',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='hearingus',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
