# Generated by Django 4.2.1 on 2023-05-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_activityofyourcompany_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstand',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book Stand', 'verbose_name_plural': 'Book Stands'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Visitor', 'verbose_name_plural': 'Visitors'},
        ),
    ]
