# Generated by Django 4.2.1 on 2023-05-22 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_bookstand_options_alter_visitor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf', models.FileField(upload_to='ticket', verbose_name='Ticket')),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_ticket', to='application.visitor', verbose_name='Visitor')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
