# Generated by Django 4.2.1 on 2023-05-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_bookstand_hear_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='activity',
            field=models.ManyToManyField(blank=True, null=True, to='application.activityofyourcompany', verbose_name='Activities'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='application.choiceofservice', verbose_name='Services'),
        ),
    ]
