# Generated by Django 4.2.1 on 2023-05-19 10:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproject',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='benifitsforvisitor',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='benifitsforvisitor',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='benifitsforvisitor',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='benifitsforvisitor',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='benifitsforvisitor',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='benifitsforvisitor',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='sub_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sub title'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='sub_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sub title'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='sub_title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sub title'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='participant',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='participant',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='participant',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='team',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='team',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='team',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Position'),
        ),
    ]
