# Generated by Django 4.2.1 on 2023-05-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutproject_name_en_aboutproject_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutproject',
            options={'ordering': ('order',), 'verbose_name': 'About Project', 'verbose_name_plural': 'About Projects'},
        ),
        migrations.AlterModelOptions(
            name='benifitsforvisitor',
            options={'ordering': ('order',), 'verbose_name': 'Benifits For Visitor', 'verbose_name_plural': 'Benifits For Visitors'},
        ),
        migrations.AlterModelOptions(
            name='exhibitor',
            options={'ordering': ('order',), 'verbose_name': 'Exhibitor', 'verbose_name_plural': 'Exhibitors'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ('order',), 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('order',), 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ('order',), 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('order',), 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
