# Generated by Django 4.2.1 on 2023-05-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_aboutproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
