# Generated by Django 4.2.1 on 2023-05-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contactus_company_name_alter_contactus_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='participant',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
    ]
