# Generated by Django 4.2.1 on 2023-05-24 13:00

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_exhibitor_link_participant_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='exhibitor/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='banner',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='main/banner', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='participant/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='partner/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='team/', verbose_name='Image'),
        ),
    ]
